// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qlkwpppjyljlnmzcapnh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFsa3dwcHBqeWxqbG5temNhcG5oIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA3NDUzNzAsImV4cCI6MjA2NjMyMTM3MH0.-XAfE_fXlFkxku2_jolUmk4pz20ieKSnWsC0hwRRbhM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);